Fix/mer 156 widget language
dividohq/finance-plugin-prestashop pull request #58
Opened 2022-01-10 13:29 UTC by dbelkad

### PR CHECKLIST

- [ ] All translations have been imported via the `make script-install-languages` command in [integrations-prestashop](https://github.com/dividohq/integrations-prestashop/blob/bc8d64ad55c25730878c29d1348f35eb5d30b9a5/Makefile#L39)
- [ ] The Changelog [CHANGELOG.md](https://github.com/dividohq/finance-plugin-prestashop/blob/51294e4669ee1bcde7e2fe34659fc1c6bb539ba6/CHANGELOG.md) has been updated with your proposed PR
- [ ] The plugin version at [financepayment/classes/DividoHelper.php](https://github.com/dividohq/finance-plugin-prestashop/blob/51294e4669ee1bcde7e2fe34659fc1c6bb539ba6/financepayment/classes/DividoHelper.php#L13) has been updated

2022-01-10 13:54 UTC, andivido requested changes
Looks good. Just gotta remove the debug and bump the plugin version

2022-01-10 13:54 UTC, andivido commented on financepayment/financepayment.php
> +            die('Ooops, something went wrong!');
Still got this debug else statement

2022-01-10 13:56 UTC, dbelkad commented on financepayment/financepayment.php
> +            die('Ooops, something went wrong!');
Ooops. Sorted

2022-01-11 10:31 UTC, andivido approved these changes

2022-01-11 10:36 UTC, merged